CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL, 
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1','RAM','DELHI' ,'9845294', 20),
('2', 'RAMESH', 'GURGAON', '7548499', 20),
('3','SUJIT','ROHTAK', '8292034', 20),
('4', 'SURESH','DELHI','8567382', 20),
('5', 'AMAN','ROHTAK', '9574333', 20),
('6', 'HARSH','GURGAON', '845729', 20);


SELECT AGE , ADDRESS
FROM STUDENT
WHERE AGE > 18 AND ADDRESS LIKE 'DELHI'

SELECT NAME , AGE 
FROM STUDENT 
WHERE NAME = 'RAM' AND AGE = 20;

SELECT NAME 
FROM STUDENT 
WHERE NAME = 'RAM' OR NAME = 'SUJIT';

SELECT NAME ,AGE 
FROM STUDENT 
WHERE NAME = 'RAM' OR AGE = 20;

SELECT NAME , AGE 
FROM STUDENT 
WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');